version: '3.2'
services:

  api:
    build:
      context: api/docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./api:/var/www
    ports:
      - "8082:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: api/docker
      dockerfile: development/php-fpm/Dockerfile
    volumes:
      - ./api:/var/www
    environment:
      PHP_IDE_CONFIG: "serverName=Docker-cms"
      APP_DEBUG: 1

  php-cli:
    build:
      context: api/docker
      dockerfile: development/php-cli/Dockerfile
    volumes:
      - ./api:/var/www
    restart: unless-stopped
    environment:
      APP_DEBUG: 1

  mysql:
    image: yobasystems/alpine-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: phonedir
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    expose:
      - "3306"
    volumes:
      - api-postgres:/var/lib/mysql
    restart: always

volumes:
  api-postgres:
